### ISSUE TITLE
Styling of output could use some work

### ISSUE THREAD

**Issue by ormiret** [OpenDataScotland/the_od_bods#10]
Some ideas

- Could do with something to make boundary between datasets clearer. 

- Similarly for fields within details for one dataset.

- Possibly put in max size for description (and have it be scrollable or expandable).

**Comment by JackGilmore** [comment]
Just checking to see what outstanding actions we have here?

- [ ] Could do with something to make boundary between datasets clearer.
  - I'm wondering whether it's worth splitting this out into a new issue and stick it under the 22Q1 milestone? This is going to require creating a new field for boundary and will need some further discussion as to how we implement that and populate the datasets accordingly
- [ ] Similarly for fields within details for one dataset. 
  - Not sure what this means?
- [ ] Possibly put in max size for description (and have it be scrollable or expandable).
    - Agree that this should be an action for this issue

**Comment by JackGilmore** [comment]
Clamped dataset description on listing page to 3 lines in https://github.com/OpenDataScotland/jkan/commit/bf284a5297a1062410a0b51633270472311f8c8d

**Comment by JackGilmore** [comment]
![image](https://user-images.githubusercontent.com/46202639/147689008-5c48eb1d-9b24-4aca-b69e-bc2c897d671d.png)

Just tested this on mobile Safari and it doesn't appear to render too well. Going to take off the CSS rule for now until I can revisit this.

**Comment by JackGilmore** [comment]
Dataset descriptions are now being truncated via javascript as of https://github.com/OpenDataScotland/jkan/commit/50936b37cb2ca0837a0afa735d42047e11e46c4a
