### ISSUE TITLE
Improve on display for Council category breakdown

### ISSUE THREAD

**Issue by KarenJewell** [OpenDataScotland/the_od_bods#102]
Improving on the back of issue #35 can we improve the styling on the table display in https://opendata.scot/analytics/local-authority-categories/?

- whitespace around the table so it doesn't spread end to end
- reduce fontsize (to allow margins)
- fixed width columns
- change colour paletter to single gradient instead of red/green

**Comment by fozy81** [comment]
Started having a look at this. Perhaps we could try turning the column names 90 degrees (vertical text).  This would make the width of the table narrower overall.

![image](https://user-images.githubusercontent.com/2878163/200396760-864710bc-deca-4a2a-854f-d2128f602d47.png)

**Comment by fozy81** [comment]
Updated table (see above PR). 

![image](https://user-images.githubusercontent.com/2878163/200663247-610023d0-a122-4d83-9d0e-d1a8c3071331.png)

@KarenJewell Does this fix issue? Happy to tweak further.

**Comment by watty62** [comment]
I like the vertical column names but I _really_ don't like using all green. The Red / Amber / Green was much better at showing what is acceptable / unacceptable levels of publishing. 

If one colour, then shades of red with deepest red as bad would be acceptable. 

Otherwise, good work, Tim. Thanks.

**Comment by JackGilmore** [comment]
I don't know if it's just me, but would it make more sense from a readability perspective for the text content to start at the bottom of the cell and go up? I.e. flipping it 180 degrees from where it is in that screenshot. 

Cheers for the work Tim!

**Comment by fozy81** [comment]
I've switch to red gradient and flipped the text the other way and removed the `text-orientation: sideways`. 

![image](https://user-images.githubusercontent.com/2878163/200939051-7541c2dd-60ab-4fb7-a9a4-18c54d4bfa97.png)
