### ISSUE TITLE
Improve Community Standards on repositories

### ISSUE THREAD

**Issue by JackGilmore** [OpenDataScotland/the_od_bods#103]
![image](https://user-images.githubusercontent.com/46202639/174360038-1608bcbf-f451-44b4-bd71-70e9a2041509.png)
Both the od_bods and jkan repos have a couple of items on the checklist that could be ticked off with a bit of documentation writing which would help when it comes to onboarding new contributors, as well as supporting the existing team.

# the_od_bods
- [x] Code of conduct
- [x] Contribution guidelines
- [x] Issue templates
- [x] Pull request template
- [x] Repository admins accept content reports

# jkan
- [x] Code of conduct
- [x] Contribution guidelines
- [x] Issue templates
- [x] Pull request template
- [x] Repository admins accept content reports

**Comment by JackGilmore** [comment]
Note: some of this being handled in #109

**Comment by JackGilmore** [comment]
Should also consider putting in place branch protection rules as part of this work so nobody can commit to main without an approved PR with passing tests.

**Comment by KarenJewell** [comment]
Adding link to community profile because I keep losing it: https://github.com/OpenDataScotland/the_od_bods/community OR the_od_bods repo>Insights>Community Standards.

Contributing guidelines added.
<img width="1034" alt="Screenshot 2022-09-13 at 11 56 33" src="https://user-images.githubusercontent.com/47697803/189883855-95a84919-102c-4583-a6e9-2fab44b66454.png">

**Comment by JackGilmore** [comment]
Something else to consider: some way for contributors without permissions for the project to request assignment to a ticket. 

At the moment contributors comment something equivalent to "I'll work on this" and a project maintainer has to go in and assign them. 

Instead we could introduce a bot command like "!assign" and it requests approval from a project maintainer via email to assign them to the ticket

**Comment by JackGilmore** [comment]
To save us having to add contributing guidelines to every project, I've moved the copy that was made in #109 to the GitHub org's .github repo which can serve up a single global contributing.md file that is used by all repos. We can still override this by placing a contributing.md in individual repos if there are differing guidelines.

Relevant commits: https://github.com/OpenDataScotland/the_od_bods/commit/bbdf9504d3ea7c82d13475eadbc2eac86aba9d86 and https://github.com/OpenDataScotland/.github/commit/d90e75de82cea0d140c71ade8e01b61d2d221d5b

There's a bunch of other community standards documents that we can have a global version of. See GitHub's docs for more info: https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/creating-a-default-community-health-file

**Comment by JackGilmore** [comment]
Have opened a PR to add some issue/PR templates and a code of conduct: https://github.com/OpenDataScotland/.github/pull/2

**Comment by JackGilmore** [comment]
![image](https://user-images.githubusercontent.com/46202639/193429903-de46b3f3-551e-413b-8f4d-aebfcea456a0.jpeg)

PR closed and we've ticked all the boxes on the Community Standards for all our repositories. 

Keeping this issue open for now though until I create another issue template for suggesting a new data portal/site/org for us to scrape. Then I think we should be good to close?

**Comment by JackGilmore** [comment]
2 new PRs and then I think we should be good to close this issue:

- (Add issue template for suggesting a new data source)[https://github.com/OpenDataScotland/the_od_bods/pull/185]
- (Create global issues config with contact links)[https://github.com/OpenDataScotland/.github/pull/3]

**Comment by JackGilmore** [comment]
All sorted now. Closing...
