### ISSUE TITLE
Tidy filetypes for datasets

### ISSUE THREAD

**Issue by KarenJewell** [OpenDataScotland/the_od_bods#105]
Filetypes for datasets are getting a bit out of hand. Currently we display them directly as provided by publisher, but inconsistencies are starting to show (e.g. "ZIP" and ".ZIP")

This should be a relatively easy solution to apply and it would be quite similar to how we tidy licensing and category information already (see https://github.com/OpenDataScotland/the_od_bods/blob/main/merge_data.py)

** Note that in https://opendata.scot/datasets.json the filetype is the resource [Name]. In https://raw.githubusercontent.com/OpenDataScotland/the_od_bods/main/data/merged_output.csv it is the [FileType]

See original conversation in slack: https://opendatascotland.slack.com/archives/C02HEHDL8AY/p1655743400444269

**Comment by JackGilmore** [comment]
Report showing current file types used in datasets: https://opendata.scot/analytics/licensing/

**Comment by watty62** [comment]
The five datasets which claim to have Atom feeds are all dead (and all belong to PKC). Other formats of the same datasets work.
