### ISSUE TITLE
Slack bot improvements

### ISSUE THREAD

**Issue by JackGilmore** [OpenDataScotland/the_od_bods#106]
Extending from #89

Potential posts:

- New GitHub PRs
- New GitHub issues/comments on issues

**Comment by KarenJewell** [comment]
New issue added to project (maybe not notes though, if we can make the distinction)

**Comment by JackGilmore** [comment]
Have added the GitHub integration to the Slack workspace so it will post notifications to the #ods-website channel when PRs or issues are created/updated/closed. Are we good to close this ticket now?

**Comment by KarenJewell** [comment]
Happy to close!
