### ISSUE TITLE
Investigate Updated Date for Aberdeenshire Council scraper

### ISSUE THREAD

**Issue by KarenJewell** [OpenDataScotland/the_od_bods#108]
Aberdeenshire Council seems to have Updated Date set to whenever the scraper is triggered. Check that the DATASET updated date is being returned, not the scraper/metadata updated date.

**Comment by KarenJewell** [comment]
Had a look at this, issue seems to be coming from how Github Actions handles it (not entirely sure how/why) but executing in local does not recreate the issue. 

Also noted that outputs from mergedata.py and export2jkan.py are different when pulled from remote than when executed in local.

**Comment by kymckay** [comment]
The good news is that I can reproduce this locally, have narrowed the issue down to occurring in the `get_last_updated` method of the scraper script. Simply looks as though `datefinder` is not correctly extracting from some strings.

The reproducible sample where it occurs for me:

`Housing Land Audit 2022 data 8th August 2022 (kmz, 188KB)`

The `datetime` object being retrieved corresponds to `2022-08-25 00:00:00` (today).

The further good news is that I've figured out what's happening while writing this comment. The `2020` in the string is parsed as an incomplete date and returned as the first result returned of the generator. I'll submit a patch to prevent this shortly.

**Comment by kymckay** [comment]
To note another slightly different case that this fixes, in case unit testing for this is ever introduced:

`gritting priority 1 and 2 footways data 22nd December 2020 (kmz, 1.4MB)`

The `1` and `2` were being considered as days of the current month.
