### ISSUE TITLE
Update docs for contribution process

### ISSUE THREAD

**Issue by KarenJewell** [OpenDataScotland/the_od_bods#109]
Update project wiki for how to contribute to the project
- if permissions are needed
- raising a PR/ draft PR
see conversation https://opendatascotland.slack.com/archives/C02HEHDL8AY/p1655919916709399

**Comment by gavbarnett** [comment]
_I'm still fairly new to forking other people's projects but from what I have gleaned so far. (Could be improved with diagrams)_:

## 1. **Fork** this project

This will create a clone of the project into your personal online GitHub account.

Normally you should fork from the head of 'main' unless you're purposefully contribution to an existing branch.

## 2. **Create a branch** on your fork of the project immediately.

Name the branch based on the feature/fix you are about to add (branch naming format? "BR_Fancy-new-feature"). Each branch should try to add only one logical feature/fix. If you want to do multiple things then make a separate branch for each. 

This means when you later issue a pull request (PR) from this branch and you are asked to make changes these are all inside a branch. This allows you to work on multiple features and PRs in parallel without conflicts.

## 3. **Make your changes** in the branch

Often this will be over multiple commits.

Try to make each commit do just one (normally fairly small) logical thing. And describe **why** you've made the change in the commit message. (_What_ you've changed is clear by the code, but **why** is often not so clear.) Also in your commit message should be any testing you performed/ or did not perform.

## 4. **Issue PR** or **Draft PR**

First ensure your project fork/branch is up to date with this repo. Do this by updating your 'main' branch from 'upstream remote' then update your feature branch from 'main'. This keeps your 'main' aligned with ours.(_I need to check that's correct_).

Check your code still works as before then do either:

A) If you have completed the feature/fix and think your code is ready for inclusion in the original project raise a PR from your branch to this repo. Your code will be reviewed before being accepted, you may receive a request for changes.

B) If you would like a review, guidance, or help completing a feature/fix you can instead issue a Draft PR from your branch to this project.

**Comment by KarenJewell** [comment]
I really butchered the last set of PRs so moving this up in priority. 
Additionally, will want to adopt and include use of BLACK for python formatting in contribution process.
https://www.geeksforgeeks.org/python-code-formatting-using-black/
https://anaconda.org/conda-forge/black

**Comment by gavbarnett** [comment]
https://github.com/firstcontributions/first-contributions

This repo walks through the process for forking, branching, and submitting PRs

**Comment by KarenJewell** [comment]
Added contributing guidelines to the_od_bods https://github.com/OpenDataScotland/the_od_bods/commit/c1a651c24f2fecaf691da4184a3bda02dbb931d0

Closing this task - future conversation and other standards should be discussed in #103
