### ISSUE TITLE
Add statistics.gov.scot as a source

### ISSUE THREAD

**Issue by KarenJewell** [OpenDataScotland/the_od_bods#114]
See this conversation in slack for context: https://opendatascotland.slack.com/archives/CGGBX81EK/p1657902404682289 

extract: The script that generates the CSV of the Scot gov SPARQL datasets, is written in Clojure. Translating it into Python to be a better fit into the ODS-website stack, would probably be straightforward for one you Python coders. Although it could also be invoked as is, by a GitHub Action (to become a component in your ODS Bot/dataset pipeline). Either might make a good exercise in a future ODS/CTC event.

**Comment by ormiret** [comment]
Clojure code that extracted our CSV: https://opendatascotland.github.io/the_od_bods/SPARQL-scotgov-import.html#/src%2Fscotgov_datasets.clj

**Comment by KarenJewell** [comment]
@heymanpreet @JackGilmore @ormiret are we happy this is done and can close?

**Comment by JackGilmore** [comment]
That's fine by me @KarenJewell

**Comment by heymanpreet** [comment]
Yup, Seems like Issue can be closed now. @KarenJewell

**Comment by KarenJewell** [comment]
Thanks all! 
With CTC27 event and commit https://github.com/OpenDataScotland/the_od_bods/commit/3e2a4a8072a80d625b92875458d8a23ee6bd004c statistics.gov.scot as a source is now added and issue will be closed.
