### ISSUE TITLE
Replace all append() with concat() in project

### ISSUE THREAD

**Issue by KarenJewell** [OpenDataScotland/the_od_bods#115]
Futureproofing for all python files: append() is going to be depreciated so should be replaced with concat() before we face legacy issues. Also will remove the warnings currently cluttering logfiles.

pd.concat([df1,df2], axis=0) should do it. The trickier part is finding them all. 

See more: https://stackoverflow.com/questions/71517750/how-to-replace-pandas-append-with-concat

**Comment by shieldo** [comment]
Linked PR should do it!

**Comment by KarenJewell** [comment]
[cd8ade7b846930e86f4cc72daf1762cb3f586d50](https://github.com/OpenDataScotland/the_od_bods/commit/cd8ade7b846930e86f4cc72daf1762cb3f586d50) and [3abbf05f7bc010bd48f9c7131f5097ba6df4ca4f](https://github.com/OpenDataScotland/the_od_bods/commit/3abbf05f7bc010bd48f9c7131f5097ba6df4ca4f) resolves this. Closing task, thanks @shieldo!
