### ISSUE TITLE
Add main.py to simplify pipeline 

### ISSUE THREAD

**Issue by gavbarnett** [OpenDataScotland/the_od_bods#121]
main.py would be able to replace much of yaml pipeline with the benefit of a clear launch point.

Using a single main.py may also allow for multi-processing/threading to speed up scrapers.

This suggestion also implies moving all other python scripts to a lower level directory to be called by main.py.

**Comment by JackGilmore** [comment]
This is a good idea. 

Ideally we should have a config to individually switch off different scraper types as this has helped in the past when testing and troubleshooting issues. For example, this is pretty easy to do in the pipeline by just commenting out the relevant line of yaml that calls the python script. 

If we were to move to a single entry script I'd also like to see some better error handling/retry logic on the individual scripts, particularly around dealing with web requests that may time out or 404. Although I appreciate it may be worth opening a separate issue to tackle that...

**Comment by gavbarnett** [comment]
Proposed structure for python files (work in progress): 
- tests/
  - pytest tests - tbd
- scripts/
  - main.py
  - sources.csv
  - tools/
    - alive.py
    - tags.py
    - export2jkan.py
    - merge_data,py
  - scrapers/
    - processor.py 
      - (needs expanded to include data type handlers / date formatting handler/ licence handling/ etc. should be used for all scrapers web or api)
    - web-based/
      - web-parser.py (new - get_headers() replacement + other common web-scraping function functions)
      - aberdeen, moray, east aryshire, nls... .py
    - api-based/
      - arcgis.py
      - dcat.py
      - usmart.py

**Comment by KarenJewell** [comment]
After reviewing PR #119 I am in full support of the above

**Comment by JackGilmore** [comment]
One thing to also keep in mind is that the CKAN scraper is still C# code so we will need to build a python script for that

**Comment by gavbarnett** [comment]
> One thing to also keep in mind is that the CKAN scraper is still C# code so we will need to build a python script for that

I think that should wait until I've got some of the initial refactoring/restructuring done of the existing ones first.

**Comment by gavbarnett** [comment]
I've started restructuring in my forked branch https://github.com/gavbarnett/the_od_bods/tree/BR-Restructuring-api-scrapers but I'm holding off even a draft PR until the testing fork gets merged as there are going to be a few minor conflicts to resolve - and the test folder will need moved into the new structure.

I'd suggest we do the restructuring in small steps until we're confident in a new structure. For example my branch is only moving the API related scrapers.
