### ISSUE TITLE
National Library Scotland Multiple Data Downloads

### ISSUE THREAD

**Issue by KarenJewell** [OpenDataScotland/the_od_bods#130]
We use a [web scraper on National Library Scotland](https://github.com/OpenDataScotland/the_od_bods/blob/main/web-scrapers/nls_scraper.py)'s pages.

The current scraper identifies the dataset as the first instance of a "Download" button if the button text matches  "Download full dataset", "Download the dataset", "Download the data" or "Download sample dataset".

But some NLS pages may have multiple download buttons for multiple datasets, as in [this example](https://data.nls.uk/data/digitised-collections/british-army-lists/) where the dataset has been split into 4 parts. Currently, only the first asset/button will be returned ("Download sample dataset"), but ideally we should retrieve all assets/buttons, which is a signficant change to the scraper approach.

Potentially: find all buttons, maybe retain all which say "download" or "data" (?), then treat each download as an asset each. In this way a page/dataset title can have more than 1 asset, as is consistent with the rest of the ODS listing.

**Comment by nutcracker22** [comment]
if you want, you can assign me to this issue.

**Comment by nutcracker22** [comment]
In the example posted by @KarenJewell, there are six download links: one sample dataset, four parts of the main dataset, and text data. A sample dataset and the text data download are also present on many other pages.

Do you want the sample datasets and text downloads in the ODS listing?

**Comment by KarenJewell** [comment]
I think it would be good to assume all assets should be scraped by default - I realise this feels redundant in this example but it will future proof it if/when the publisher modifies an existing listing or adds a new one with e.g. 10 parts. (And I would bet money all 10 parts will be named differently also 🙃)

Scraping all assets this way will mean, in this example, 6 assets but stil 1 dataset. i.e. we will see 6 instances(rows) in merge_data.py's output (the .csv file) but 1 jkan instance after export2jkan.py (1 .json file). It would show up as 6 links on 1 dataset page.

**Comment by nutcracker22** [comment]
okay, I agree with that. And this makes it easier to code ;)
