### ISSUE TITLE
Fix NLS Licensing Treatment

### ISSUE THREAD

**Issue by KarenJewell** [OpenDataScotland/the_od_bods#133]
Having removed licencing treatment in the NLS Scraper https://github.com/OpenDataScotland/the_od_bods/commit/56c70c9b63b68fc00324be633f7a086af862cda0 has knock on effects in end results.

Correct this such that processing is done in merge_data.py but NLS scraper needs to return 1 licence as string. It's currently a list and some assets have multiple licences. Might want to consider why an asset SHOULD have more than 1 licence. Consider also existing PR https://github.com/OpenDataScotland/the_od_bods/pull/128

https://opendatascotland.slack.com/archives/C02HEHDL8AY/p1662122527467149?thread_ts=1662122284.974809&cid=C02HEHDL8AY
![image](https://user-images.githubusercontent.com/47697803/188674083-3aaae543-bf7e-469d-aeda-5f2528325199.png)

**Comment by nutcracker22** [comment]
multiple licences are mentioned in [https://data.nls.uk/data/digitised-collections/encyclopaedia-britannica/](https://data.nls.uk/data/digitised-collections/encyclopaedia-britannica/) and [https://data.nls.uk/data/digitised-collections/scottish-exams/](https://data.nls.uk/data/digitised-collections/scottish-exams/). In both cases the files are not separated according to licence, but combined in one zip file. How should these cases be treated?
