### ISSUE TITLE
Add Scottish Qualifications Authority (SQA) as a source

### ISSUE THREAD

**Issue by KarenJewell** [OpenDataScotland/the_od_bods#136]
https://www.sqa.org.uk/sqa/57523.html

**Comment by nutcracker22** [comment]
I'm working on it

**Comment by nutcracker22** [comment]
see #161. Suggestions for improving this draft are very welcome :)

**Comment by JackGilmore** [comment]
Thanks @nutcracker22. We'll take a look at this soon 😊
