### ISSUE TITLE
Add ScotRail audio announcements

### ISSUE THREAD

**Issue by JackGilmore** [OpenDataScotland/the_od_bods#137]
All the ScotRail audio announcements snippets have been split into audio files and tagged with relevant metadata after a recent FOI. 

Should we stick this in as a data source in the datasets or maybe in the resources list as it's technically a good use of open/FOI data?

Source: https://simonwillison.net/2022/Aug/21/scotrail/

**Comment by KarenJewell** [comment]
@JackGilmore done and can close?

**Comment by JackGilmore** [comment]
LGTM
