### ISSUE TITLE
Add analytics output to docs/ so it's picked up by pages

### ISSUE THREAD

**Issue by ormiret** [OpenDataScotland/the_od_bods#15]
Have github pages displaying docs/ folder (on fork - the main CodeTheCity site blocks using pages for this repo). 

Add the analytics output there. 

Could also do with a link to it from `index.html`

**Comment by KarenJewell** [comment]
I can update the link in index.html... but I need to figure out how to automate analysis.html generation and have it save in the 2 locations. Currently this is done manually at terminal.

Possibly a shell script that will update analysis.ipynb + generate analysis.html. This is currently in terminal
`jupyter nbconvert <filename>.ipynb --to html --TemplateExporter.exclude_input=True --no-prompt
`

**Comment by ormiret** [comment]
I've added a bash script to run that command to generate `analytics.html` and the copy it to `docs/`

**Comment by KarenJewell** [comment]
The original task is redundant now we have moved to the new style of pages: https://opendata.scot/analytics/
Closing task.
