### ISSUE TITLE
Update tests for sources using processor.py

### ISSUE THREAD

**Issue by KarenJewell** [OpenDataScotland/the_od_bods#151]
Changes to the processor.py file means expected output for tests need to be updated.

**Comment by gavbarnett** [comment]
I can have a look at this :-)

**Comment by KarenJewell** [comment]
That's grand thanks. I got as far as changing the source files so structure is ok. 
But because we are using exact copies of data files (including content) it seems to be failing where the content between expected output (static) and test output (generated) is significantly different - in the cases I've seen, where the order of the content is different. So this makes it really easy to fail since we don't consistently order the content post-retrieval.

I also have much much bigger questions about whether we should be using exact copies of data, rather than making a dummy set of data for test purposes only. Exact copies of data will age really quickly.

See what you think?

**Comment by gavbarnett** [comment]
got it working locally.
bug 1 - generate mock data tries to get new data for new data sources (add at CTC) and this causes issues - can mask these for now.
bug 2 - dcat.py has a bug on line 47. ds[8] should be ds[9] now.

**Comment by gavbarnett** [comment]
I'm not sure I follow on the test data? it's a copy but that's in order to make it static.
Obviously we need to update the csv compare files if we change the headers / ordering. I could split the data source update from the csvs expected update.

**Comment by gavbarnett** [comment]
on bug 1:
change line 67 in generate_new_mock_data.py to: `if url_list[name]["type"] in ["USMART", "dcat", "arcgis"]:`

**Comment by gavbarnett** [comment]
generate_new_mock_data.py could certainly be improved. likely you'd like it to be more selective in what it does, rather than a blanket update of everything. but that's a separate issue/feature

**Comment by gavbarnett** [comment]
I'll sort it out :-)

**Comment by gavbarnett** [comment]
bug 3 - csv checker needs a new checker for valid filenames `{"title": "FileName", "test_func": is_valid_filename},` - which for now i'll just make as a basic string check

**Comment by gavbarnett** [comment]
see #158 PR. I fixed it :-)
You can close this one is you like.

**Comment by KarenJewell** [comment]
[PR #158 ](https://github.com/OpenDataScotland/the_od_bods/pull/158) closes this. Keen to follow up on @gavbarnett's point about improving generate_new_mock_data.py so have opened #159 for it.
