### ISSUE TITLE
Improve dependency management and documentation

### ISSUE THREAD

**Issue by kymckay** [OpenDataScotland/the_od_bods#155]
When setting up for development I had to inspect the GitHub actions to quickly find the dependencies to install. I recommend maintaining a `requirements.txt` file:

- To ensure a consistent environment across contributor machines 
- Enable easy setup for less experienced (perhaps first time) contributors (`pip install -r requirements.txt`)
- Simplify the environment setup in the GitHub actions (same as above)
- Document all of the dependencies in a common place
- Manage dependency versioning (not always installing latest and being exposed to upstream breakage)

Useful explanation if unfamiliar with common practices: https://towardsdatascience.com/requirements-vs-setuptools-python-ae3ee66e28af

**Comment by kymckay** [comment]
On the back of this, dependabot can be setup to check for version updates on an interval and submit pull requests for review to automatically manage the requirements.txt file

Give me a ping if help wanted at all with this.

**Comment by JackGilmore** [comment]
Had opened #85 to deal with this a while ago but forgot about it. Given that you've provided much more detail than my one sentence issue I wrote on the fly, I'll close mine as a duplicate and hopefully look into this soon
