### ISSUE TITLE
Add name conversion for publisher "Na h-Eileanan an Iar" to "Comhairle nan Eilean Siar"

### ISSUE THREAD

**Issue by KarenJewell** [OpenDataScotland/the_od_bods#164]
**Describe the bug**
For some reason, datasets by the Local Authority "Comhairle nan Eilean Siar" are being published under its constituency name "Na h-Eileanan an Iar" instead. The LA name on JKAN orgs is correct, so not going to change that, but we need to treat the incoming feed so it matches the org name. 
Sources: 
https://archive2021.parliament.scot/visitandlearn/94334.aspx and 
https://en.wikipedia.org/wiki/Comhairle_nan_Eilean_Siar

There is already an existing function in merge_data.py for renaming publishers, this should just be an additional instance to it.

**To Reproduce**
N/A

**Expected behavior**
Datasets currently listed under publisher "Na h-Eileanan an Iar" should display "Comhairle nan Eilean Siar" instead.
These same datasets should appear listed under the Comhairle nan Eilean Siar [organisation page](https://opendata.scot/organizations/comhairle_nan_eilean_siar/)
The [Local Authority Coverage page](https://opendata.scot/analytics/local-authority-coverage/) should show at least 1 count for Comhairle nan Eilean Siar and the total council count at the top should read 31 instead of 30. 

**Screenshots**
[Example] (https://opendata.scot/datasets/na+h-eileanan+an+iar-community+council+boundaries+-+na+h-eileanan+an+iar/)

**Hardware and software used**
N/A

**Additional context**
None

**Comment by fozy81** [comment]
Hi @KarenJewell  I've made a PR for this issue. I think it's fixes it, but not sure how to test this locally.

**Comment by KarenJewell** [comment]
Closed with PR #202
