### ISSUE TITLE
Add Scottish Forestry as source

### ISSUE THREAD

**Issue by KarenJewell** [OpenDataScotland/the_od_bods#180]
**Is your feature request related to a problem? Please describe.**
Scottish Forestry have an open data portal and it looks like it's on arcgis so we may be able to use our existing arcgis extractor.
https://open-data-scottishforestry.hub.arcgis.com/

**Comment by JackGilmore** [comment]
Note: need to add a new organization record to opendata.scot JKAN as we don't have one for Scottish Forestry

**Comment by KarenJewell** [comment]
Resolved by PR #186  and new issue #187 added for creating the missing org listing. Closing issue.
