### ISSUE TITLE
Fix Scottish Forestry Organisation

### ISSUE THREAD

**Issue by KarenJewell** [OpenDataScotland/the_od_bods#187]
**Describe the bug**
A 2-part issue:
- Scottish Forestry is missing an entry in [jkan/_organizations ](https://github.com/OpenDataScotland/jkan/tree/gh-pages/_organizations)(twitter @scotforestry, website https://forestry.gov.scot/)
- Publisher name for Scottish Forestry is also not coming though correctly. 

**To Reproduce**
1. Search for "Forestry" in page Organizations
2. Search for "Forestry" in page Datasets

**Expected behavior**
When searching for "Forestry" in Organizations, "Scottish Forestry" should appear.
When searching for "Forestry" in Datasets, the publisher name should be `Scottish Forestry` instead of `Scottish.Forestry`.

**Screenshots**
![Screenshot 2022-10-07 at 22 47 38](https://user-images.githubusercontent.com/47697803/194668160-9cedd68a-410a-440e-b343-20925ad5aead.png)

**Hardware and software used**
- Browser: Firefox 105.0.1 (64-bit)

**Additional context**
Not investigated where the `Scottish.Forestry` labelling is happening.

**Comment by JackGilmore** [comment]
I'll grab this

**Comment by JackGilmore** [comment]
New pull requests to handle issues
https://github.com/OpenDataScotland/the_od_bods/pull/188
https://github.com/OpenDataScotland/jkan/pull/3
