### ISSUE TITLE
Bug in the Aberdeenshire scraper

### ISSUE THREAD

**Issue by k7ragav** [OpenDataScotland/the_od_bods#204]
**Describe the bug**
The manual tags in the webscraper are not getting mapped correctly. 

**To Reproduce**
1. Go to https://github.com/OpenDataScotland/the_od_bods/blob/main/data/scraped-results/aberdeenshire.csv
2. Click on the file
3. Scroll down to 'Committee areas boundaries within Aberdeenshire' and you will see that manual tag is given as 'transport'  instead of 'council and government'

**Expected behavior**
The manual tag mapping needs to be done correctly 

**Screenshots**
None

**Hardware and software used**
 - Device: laptop
 - OS: windows
 - Python version - 3.9

**Additional context**
None

**Comment by nutcracker22** [comment]
I just had a look at the mentioned csv file. There are only three categories present: `education`, `burial grounds`, and `transport`, with transport being the most occurring category. These categories are also the first three handled in [aberdeenshire_council_scraper.py](https://github.com/OpenDataScotland/the_od_bods/blob/main/web-scrapers/aberdeenshire_council_scraper.py#L105), with `transport` being the third. So I would guess, the error is in the `elif` for `transport.`

**Comment by KarenJewell** [comment]
hmm, wonder why we're even processing categories at the scraper level. Should be at merge_data.py level.

**Comment by nutcracker22** [comment]
This point is very valid @KarenJewell :D For me it was just: code was there, it was broken, so I fixed it. And it was a welcome excuse not to focus on my studies :D

I'll check, whether the key words are already implemented in merge_data.py and then update the PR.
