### ISSUE TITLE
Add Scottish Parliament data as a source

### ISSUE THREAD

**Issue by watty62** [OpenDataScotland/the_od_bods#208]
**Link to the data source**
Data : https://data.parliament.scot/#/datasets 

API: https://data.parliament.scot/#/api-list 

https://data.parliament.scot/#/home

**Data source type (if known)**
Unknown

**Organization(s) the data belongs to**
Scottish Parliament

**What licences are applied to the data being published? (if known)**
It was using a version of OGL3 in 2020. "being released under "Scottish Parliament Licence is aligned with OGLv3.0"

But the link from https://data.parliament.scot/#/about to the reuse conditions is now broken. 

**Additional information**
We don't have a Scottish Parliament yet set up as an ODS Organisation

**Comment by JackGilmore** [comment]
Added Scottish Parliament as an org as of OpenDataScotland/jkan@16c403e0f082c3f517399dc8e94e0630432286d0. 

Will give them an email on the address listed on the Notes page to see if I can get clarification on licencing.

**Comment by JackGilmore** [comment]
Reply from Scottish Parliament confirming that datasets are available under the Scottish Parliament Copyright Policy:

> Dear Jack,
> 
> Thanks for getting in touch. 
> 
> You are free to use the Open Data sets contained in the Scottish Parliament’s open data portal. As advised in the Notes section of the open data portal, open data falls under our policy on use of SPCB Copyright Material. You can access information about the Scottish Parliament Copyright Policy at the following link: [Copyright | Scottish Parliament Website](https://www.parliament.scot/about/copyright) 
> 
> This provides that material published by the Scottish Parliamentary Corporate Body (SPCB) may be reproduced without formal permission subject to the Copyright Licence. Where any material is republished or copied for use the source of the material must be acknowledged by including the following attribution statement and, where possible, providing a link to the licence:
> “Contains information licensed under the Scottish Parliament Copyright Licence”.
> 
>  Hope you find this information to be of assistance.
> 
> Kind regards 
> 
> Robin
>  
> 
> **Robin Davidson**
> Head of Information Governance and Data Protection Officer

**Comment by watty62** [comment]
This page is particularly confusing: https://www.parliament.scot/about/copyright 

It speaks about the Scottish Parliament copyright licence but at the end cuts and pastes, it appears, a chunk about the OGL3. 

Nowhere in the main body of that page is OGL3 mentioned, that i can see, until the pasted in section. 

So, to me it looks like there is nothing in SPCL section that says that it incorporates, or includes the terms of OGL3. 

Am I wrong?

**Comment by JackGilmore** [comment]
A strange one, yes. Particularly annoying when I asked if they could update their dataset metadata to include the licence or to update the link on the Notes page that 404s. Both requests seem to have fallen on deaf ears. 

In this case, I think we'll just treat the licence as "Scottish Parliament Copyright Licence", which I have hard coded into the script I'm working on. I've also added the licence in JKAN in preparation for including these datasets.
