### ISSUE TITLE
CSV to YAML/MD generator

### ISSUE THREAD

**Issue by JackGilmore** [OpenDataScotland/the_od_bods#21]
Datasets and organisations in JKAN are stored in separate markdown files which contain YAML:
- https://github.com/OpenDataScotland/jkan/tree/gh-pages/_datasets
- https://github.com/OpenDataScotland/jkan/tree/gh-pages/_organizations

It might be handy if we could write a CSV to YAML/MD script that takes in a CSV and writes each row out as a markdown file containing YAML

**Comment by watty62** [comment]
I've not looked at this in any depth but this might help  [https://github.com/josue-rojas/csv-yaml](https://github.com/josue-rojas/csv-yaml )

**Comment by JackGilmore** [comment]
> I've not looked at this in any depth but this might help https://github.com/josue-rojas/csv-yaml

Looks like this does 1 CSV to 1 YAML file whereas we're looking for 1 CSV to multiple YAML files. May be something that can be forked and adapted though to meet our needs

**Comment by ormiret** [comment]
I'd do the generation with rendering jinja template for each md file we need. 

I've got a first swing at that in `jkan-gneration-test` branch

**Comment by ormiret** [comment]
Switched to using `pyyaml` to generate the YAML block. 

Working version of this in `export2jkan.py` now
