### ISSUE TITLE
Perth & Kinross Council datasets have owner mismatch

### ISSUE THREAD

**Issue by KarenJewell** [OpenDataScotland/the_od_bods#217]
**Describe the bug**
Perth and Kinross council are publishing datasets under owner "Perth & Kinross Council" but are in our system as "Perth and Kinross Council". This means datasets are not being correctly linked and we're seeing 2 orgs "Perth & Kinross Council" with 68 datasets and "Perth and Kinross Council" with 14 datasets

**To Reproduce**
N/A

**Expected behavior**
Correct name should be "Perth & Kinross" which matches the council website.

**Screenshots**
<img width="270" alt="Screenshot 2023-02-18 at 14 00 47" src="https://user-images.githubusercontent.com/47697803/219869908-8f7ff640-2d3b-41f8-9cf9-66321059b0b3.png">

**Hardware and software used**
N/A

**Additional context**
None

**Comment by JackGilmore** [comment]
Was away to add a comment saying this can be fixed by adding another mapping in `merge_data.py` but just noticed you've done that 😂
