### ISSUE TITLE
Add extra fields to organisations listing

### ISSUE THREAD

**Issue by KarenJewell** [OpenDataScotland/the_od_bods#23]
- [x] OD portal URL 
- [x] org URL
- [x] Twitter handle

**Comment by JackGilmore** [comment]
Couple of suggestions from me:
- Org type (local authority, central gov, third sector etc.)
- GSS code (if applicable)
- OD portal type (CKAN, ArcGIS, webpage)

**Comment by watty62** [comment]
Jurisdiction / coverage

eg https://w.wiki/4Kd6

**Comment by JackGilmore** [comment]
Some potential inspiration for other fields: https://github.com/GFDRR/rdl-jkan

**Comment by watty62** [comment]
Wikidata QID for organisation

**Comment by JackGilmore** [comment]
Had a play around and added in an organization type lookup and got the value to display on the org index and org record page. Additional types can be added to the dropdown via this file: https://github.com/OpenDataScotland/jkan/blob/gh-pages/_data/org_types.yml

![image](https://user-images.githubusercontent.com/46202639/143496157-01a1e19e-1d5e-4ec9-b677-3ccac9d2acdc.png)
![image](https://user-images.githubusercontent.com/46202639/143496174-52ef77a5-0198-451f-a4fd-40a3ca45e39e.png)
![image](https://user-images.githubusercontent.com/46202639/143496213-3a405be9-e6b9-4af5-8820-0cc9143fa8f5.png)

**Comment by JackGilmore** [comment]
Added some fields in [18f2abd4335b95abdc508e65243a2b63400a5658](https://github.com/OpenDataScotland/jkan/commit/18f2abd4335b95abdc508e65243a2b63400a5658)

**Comment by JackGilmore** [comment]
Added portal type in f7c0e41804ca5134e5b5b219128196a3f1d339fe and 14cbf68351913408a9193221d4163d4eba51ac5f.

Think we can close this now and add Jurisdiction / Coverage in another issue? @KarenJewell

**Comment by KarenJewell** [comment]
Opened #58. closing this task
