### ISSUE TITLE
Add ability to filter datasets by criteria

### ISSUE THREAD

**Issue by KarenJewell** [OpenDataScotland/the_od_bods#26]
Expected criteria:

- [x] Region/ source
- [x] File format
- [x] Category
- [ ] Time (Year categories)
- [ ] Live status

**Comment by KarenJewell** [comment]
This may be resolved by completion of #20. But will leave this issue open as part of testing that #20 is implemented ok. Filter functionality is expected to be an out-of-the-box feature of JKAN.

**Comment by JackGilmore** [comment]
Have checked off region/source and category from the list above as these are provided as default in JKAN. If we want to add additional filtering then we will probably need to program this ourselves.

**Comment by JackGilmore** [comment]
There are half a dozen OD portals from universities which have a high volume (3 with 1000+) of research related datasets which outweighs the presence of other public sector datasets at the moment: https://github.com/watty62/SOD/blob/master/FE.md

As a result, should we consider adding the ability to filter datasets by organisation type?

**Comment by KarenJewell** [comment]
Separated outstanding actions into issues #59 #60 and #61. Closing task.
