### ISSUE TITLE
Research - what are the other sources we can add?

### ISSUE THREAD

**Issue by KarenJewell** [OpenDataScotland/the_od_bods#32]
- Public sector
- Air Aberdeen
- FOI reports?

**Comment by watty62** [comment]
We have currently these organisation types: 
https://github.com/OpenDataScotland/jkan/blob/gh-pages/_data/org_types.yml

These cover these organisations:
https://opendata.scot/organizations/

More sources here? 

https://github.com/watty62/SOD

**Comment by JackGilmore** [comment]
FOIs can be pulled through for organizations with a WhatDoTheyKnow ID as a JSON feed. Should be able to display them on the page using some JavaScript: https://www.whatdotheyknow.com/feed/body/aberdeen_city_council.json

**Comment by JackGilmore** [comment]
@KarenJewell Do you reckon we can close this one? Any relevant data portal we've identified has its own individual GitHub issue at this point.

**Comment by KarenJewell** [comment]
Agree to close.
