### ISSUE TITLE
Publish a page showing our project goals + web analytics

### ISSUE THREAD

**Issue by KarenJewell** [OpenDataScotland/the_od_bods#33]

**Comment by KarenJewell** [comment]
[matomo](https://matomo.wikimedia.se/index.php?module=CoreHome&action=index&idSite=7&period=day&date=yesterday#?idSite=7&period=day&date=yesterday&segment=&category=Dashboard_Dashboard&subcategory=1) was suggested at CTC24 as an alternative to google analytics

**Comment by KarenJewell** [comment]
Also from duplicate note: Do we need access analytics? (to prove success of project)
Page analytics - record visits and clickthroughs.

**Comment by JackGilmore** [comment]
Looking at matomo and if we wanted to use this we've got two options:
- Pay [€19 a month](https://matomo.org/pricing/) for cloud hosting
- Self-host which would require:
    - Web server that supports PHP
    - A MySQL db

I'm thinking that the latter option is the most feasible if we go for Matomo. I had a look at trying to set up a PHP server using Heroku (which we already have a free account for the JKAN auth server) but it looks like installing an SQL database add-on requires a credit card to be added to the account even for the free usage plan.

![image](https://user-images.githubusercontent.com/46202639/147653933-98ab4bb5-1962-4219-93f8-f1ea188ee1db.png)

@watty62 @KarenJewell wondering what your thoughts are on this?

The easier and cheaper (free) alternative would be Google Analytics, although I know not everyone may be keen on this due to privacy concerns.

**Comment by KarenJewell** [comment]
Here's another potential option, but it's not free either? And I'm totally ignorant to what's involved in setting it up https://plausible.io/

**Comment by KarenJewell** [comment]
plausible was set up on 6 Apr with a 30-day free trial. live analytics is available from https://plausible.io/opendata.scot.

Next things to do are:
- embed web analytics into opendata.scot - probably in /About
- convert free trial to paid subscription ~£90 a year

**Comment by JackGilmore** [comment]
Plausible also has a [documented API](https://plausible.io/docs/stats-api) for programmatically extracting site stats. This may be useful if we want to extract visitor stats for the dataset or org pages and lay out a leaderboard of which are the top 10 most visited. Example API response for page data below:
```json
{
    "results": [
        {
            "bounce_rate": 47,
            "events": 50,
            "page": "/",
            "pageviews": 50,
            "visit_duration": 82,
            "visitors": 40,
            "visits": 38
        },
        {
            "bounce_rate": 86,
            "events": 30,
            "page": "/datasets/City of Edinburgh Council-586/",
            "pageviews": 30,
            "visit_duration": 14,
            "visitors": 29,
            "visits": 29
        },
        {
            "bounce_rate": 0,
            "events": 51,
            "page": "/datasets/",
            "pageviews": 51,
            "visit_duration": 181,
            "visitors": 19,
            "visits": 1
        },
        {
            "bounce_rate": null,
            "events": 4,
            "page": "/analytics/",
            "pageviews": 4,
            "visit_duration": null,
            "visitors": 4,
            "visits": null
        },
        {
            "bounce_rate": null,
            "events": 3,
            "page": "/about/",
            "pageviews": 3,
            "visit_duration": null,
            "visitors": 3,
            "visits": null
        },
        {
            "bounce_rate": null,
            "events": 2,
            "page": "/organizations/",
            "pageviews": 2,
            "visit_duration": null,
            "visitors": 2,
            "visits": null
        },
        {
            "bounce_rate": null,
            "events": 2,
            "page": "/suggest-dataset/",
            "pageviews": 2,
            "visit_duration": null,
            "visitors": 2,
            "visits": null
        },
        {
            "bounce_rate": null,
            "events": 2,
            "page": "/datasets/Scottish Government-689/",
            "pageviews": 2,
            "visit_duration": null,
            "visitors": 2,
            "visits": null
        },
        {
            "bounce_rate": 0,
            "events": 2,
            "page": "/datasets/Glasgow City Council-622/",
            "pageviews": 2,
            "visit_duration": 0,
            "visitors": 2,
            "visits": 1
        },
        {
            "bounce_rate": null,
            "events": 1,
            "page": "/datasets/Angus Council-138/",
            "pageviews": 1,
            "visit_duration": null,
            "visitors": 1,
            "visits": null
        },
        {
            "bounce_rate": null,
            "events": 1,
            "page": "/datasets/Aberdeen City Council-0/",
            "pageviews": 1,
            "visit_duration": null,
            "visitors": 1,
            "visits": null
        },
        {
            "bounce_rate": null,
            "events": 1,
            "page": "/datasets/VisitScotland-860/",
            "pageviews": 1,
            "visit_duration": null,
            "visitors": 1,
            "visits": null
        },
        {
            "bounce_rate": null,
            "events": 1,
            "page": "/datasets/Cycling Scotland-515/",
            "pageviews": 1,
            "visit_duration": null,
            "visitors": 1,
            "visits": null
        },
        {
            "bounce_rate": null,
            "events": 2,
            "page": "/datasets/Glasgow City Council-632/",
            "pageviews": 2,
            "visit_duration": null,
            "visitors": 1,
            "visits": null
        }
    ]
}
```

**Comment by KarenJewell** [comment]
dashboard is embedded in https://opendata.scot/about/siteanalytics/
left to do:
- convert free trial to paid subscription ~£90 a year
- put instructions somewhere for public to access stats via API

**Comment by JackGilmore** [comment]
> * put instructions somewhere for public to access stats via API

This wouldn't be possible to give the public direct access to the Plausible API for our site as it requires API key authentication which gives them access to other things we wouldn't want them to access e.g. adding/deleting sites from our analytics account. 

As an alternative, once we get to the automation stage we can set up a daily GitHub Actions job to pull the previous day's stats and save them as a file on the repo.

**Comment by JackGilmore** [comment]
![image](https://user-images.githubusercontent.com/46202639/164197739-6efd3fba-c871-42a7-9981-b87b2daeadd9.png)
Yup, all looking good!

Automating the pulling of analytics data would maybe be a good example project to run through to show how GitHub Actions works as well 😄

**Comment by JackGilmore** [comment]
@KarenJewell Reckon we can close this one now?

**Comment by KarenJewell** [comment]
indeed we can!
