### ISSUE TITLE
Automate table of expected data categories for each council

### ISSUE THREAD

**Issue by KarenJewell** [OpenDataScotland/the_od_bods#36]
From slack 8 Nov:
Ian Watt
I like this custom scripting in this Wikidata Wiki which queries via SPARQL and calculates completeness:
https://www.wikidata.org/wiki/User:Jason.nlw/NLW_Authority

NiVZ
That's neat. Could measure completeness of each authorities data sets across the rows or completeness of the data set across Councils down the columns (or both)

Ian Watt
Yes. It's working on Wikidata - but its method could work.

**Comment by KarenJewell** [comment]
Dependent on https://github.com/OpenDataScotland/the_od_bods/projects/1#card-72472758 being completed first.

**Comment by JackGilmore** [comment]
Implemented in https://github.com/OpenDataScotland/jkan/commit/96bd44b830a67af278faf4f5b51e7a8346aaf77b
