### ISSUE TITLE
Allow users to make a suggestion for datasets they would like to have

### ISSUE THREAD

**Issue by KarenJewell** [OpenDataScotland/the_od_bods#37]
Should have
- short title
- longer description
- category(?)

This is aimed at Civic/Citizen coders or Power Users - the people who turn OD into products for end-users. 
It shouldn't be year specific or even LA specific, that's what would make it different from an FOI request. Just a general wishlist of "if we could have data about... car parking spaces", for example.

We did have some good suggestions come through from SODU2021. We may want to collate them together

We may also want to provide in the interface, an example of a suggestion: e.g. "I would like to have data about street parking restrictions" or "could we have data about how many live christmas trees are discarded?" just to guide the style of suggestion and make it clear this is NOT A REQUEST.

The intention is: with enough suggestions, we can share what type of data is most desired. 

We could also live publish the suggestions, but that's for a later stage (potentially 21Q3 automation)

**Comment by JackGilmore** [comment]
We could possibly set up a Google Form to capture this data and display it on the site. That way users can suggest datasets without having to log it as an issue on the GitHub repository.

I found this interesting article about taking a Google Sheet and outputting it as JSON. We could take the JSON and output it on a page on our JKAN frontend to display the list of suggested datasets: https://benborgers.com/posts/google-sheets-json

**Comment by JackGilmore** [comment]
![image](https://user-images.githubusercontent.com/46202639/141196811-c38fab97-1571-4fe9-bc6c-fbfa0d1cb72e.png)
Or alternatively, if we don't want to go through someone else's API, it looks like Google Sheets natively supports publishing as CSV

**Comment by KarenJewell** [comment]
@JackGilmore's done this 🥳 - closing task
https://github.com/OpenDataScotland/jkan/commit/4ab04770ca82ecdb3882577e58372b2987d50983

**Comment by JackGilmore** [comment]
Suggest a dataset is all up and running. Filling out the Google form will put the result in the table https://opendata.scot/suggest-dataset/

Google Form and sheet is currently hosted under my personal account at the moment. We might want to create an ODS Google account (if one doesn't already exist?) so we can host the form and sheet under there. Might also be helpful if we want to spin up Google Analytics to solve #33
