### ISSUE TITLE
Import data for each public sector organisation from Wikidata queries

### ISSUE THREAD

**Issue by watty62** [OpenDataScotland/the_od_bods#39]
Import data on organisations such as this [https://w.wiki/4TBe](https://w.wiki/4TBe) for local authorities. 

Ian has a list of tweaked queries for health boards, HSCPs, NDPBs etc. 

Format the output for each as an MD file in here [https://github.com/OpenDataScotland/jkan/tree/gh-pages/_organizations](https://github.com/OpenDataScotland/jkan/tree/gh-pages/_organizations)

**Comment by JackGilmore** [comment]
Do we want to add the [universities with open data portals](https://github.com/watty62/SOD/blob/master/FE.md) and then consider this issue closed?

**Comment by watty62** [comment]
Added all 6 Universities. I think this can be closed now?
