### ISSUE TITLE
tidy licensing categories in JKAN layer

### ISSUE THREAD

**Issue by KarenJewell** [OpenDataScotland/the_od_bods#42]
licensing labels which come in through the raw scraped data need to be mapped to... something?

This should be done in an intermediary processing layer between raw data and presented data (we want to retain the raw messy data for analytics).

**Comment by ormiret** [comment]
Have some of this translation now: https://github.com/OpenDataScotland/the_od_bods/commit/0b7b4f5bf88ac00c9af8b12f339dae84b4f0b303

Unhandled strings from current data:
```
Unknown license:  Public Sector End User Licence (Scotland)
Unknown license:  
Unknown license:  other-closed
Unknown license:  Other (Public Domain)
Unknown license:  INSPIRE Regulations 2009
Unknown license:  Custom
```

**Comment by KarenJewell** [comment]
tidying done in the merge_data layer. Can't really do much about custom licences, but these are treated as nulls in the extract2jkan layer anyway. Marking as closed. Until more licences come our way...
