### ISSUE TITLE
Success stories page

### ISSUE THREAD

**Issue by JackGilmore** [OpenDataScotland/the_od_bods#43]
Create a page to display some success stories and case studies of open data in Scotland. Could include examples from previous CTCs such as OpenWasteMap.

**Comment by JackGilmore** [comment]
Also look at success stories discussed at SODU2021

**Comment by KarenJewell** [comment]
@JackGilmore could we say /Resources has satisfied this for now and happy to close? I've extracted the projects and links from the SODU21 board.

**Comment by JackGilmore** [comment]
> @JackGilmore could we say /Resources has satisfied this for now and happy to close? I've extracted the projects and links from the SODU21 board.

Agreed. Happy for this to be closed 😊

**Comment by KarenJewell** [comment]
nice. 👍
