### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by ormiret** [OpenDataScotland/the_od_bods#52]
I've noticed a link getting broken somewhere along the chain. 

For https://opendata.scot/datasets/Aberdeen%20City%20Council%20-%20Community%20Councils%202018/ the CSV link is truncated to:
`http://spatialdata-accabdn.opendata.arcgis.com/datasets/8495099e41234f03ba6679f1236f2749_0.csv?outSR={`
should be:
`http://spatialdata-accabdn.opendata.arcgis.com/datasets/8495099e41234f03ba6679f1236f2749_0.csv?outSR={%22latestWkid%22:27700,%22wkid%22:27700}` 

Something choking on the quotes at some point in the chain?

**Comment by ormiret** [comment]
in this case the link still seems to work, so maybe not too much of a problem

**Comment by JackGilmore** [comment]
This doesn't appear to be relevant anymore. Closing.
