### ISSUE TITLE
Enhance info for file links

### ISSUE THREAD

**Issue by watty62** [OpenDataScotland/the_od_bods#55]
On this page: https://opendata.scot/datasets/Public%20Health%20Scotland-239/ the user is presented with abut 75 CSV links with no context. 

On the page on the data hosts site https://www.opendata.nhs.scot/dataset/prescriptions-in-the-community the metadata of the file (month / year) is presented. 

Can we pull that through in some way to make the ODS page more usable?

**Comment by JackGilmore** [comment]
CKAN API endpoint for this dataset: https://www.opendata.nhs.scot/api/3/action/package_show?id=prescriptions-in-the-community

The API response returns properties for name and description of each data file so we can easily pull those through for CKAN datasets. Not sure about the rest of the APIs though. 

If we were to do that we probably want to change this big bullet pointed list into a searchable/filterable table.

**Comment by KarenJewell** [comment]
Displaying filename could be a good next step, although some filenames may not be helpful either to end user.

**Comment by JackGilmore** [comment]
From the looks of our current `export2jkan.py` we are writing the FileType column from our CSVs as the name of the file that gets read by JKAN. I would propose that we add a new column to our CSV files called `FileName` so we can start passing these through into JKAN?

**Comment by KarenJewell** [comment]
The link in original comment https://opendata.scot/datasets/Public%20Health%20Scotland-239/  is now a deadlink, replaced with: https://opendata.scot/datasets/public+health+scotland-prescriptions+in+the+community/

**Comment by KarenJewell** [comment]
In export2jkan.py, lines 156-160  
```
y["resources"] = [
        {"name": d.file_type, "url": d.url, "format": d.file_type}
        for d in ds.files
        if d.url
    ]
```
The fix is to change `"name": d.file_type` to something else. 
Potentially could use **filename** which exists in f but not pulled into ds or d where f/ds/d. 
HOWEVER. 
Filenames are inconsistent and incomplete, of course, and needs treatment for nulls potentially in the merge_data.py step before. So a few cascading changes here.
