### ISSUE TITLE
Auto-extract and publish opendata.scot site analytics from plausible

### ISSUE THREAD

**Issue by KarenJewell** [OpenDataScotland/the_od_bods#57]
Stemming from task #33 - create an auto-publishing source/stream of opendata.scot site analytics for users. Suggestion is to use Github Actions to achieve this.

**Comment by JackGilmore** [comment]
Done in https://github.com/OpenDataScotland/opendata.scot_pipeline 🎆

**Comment by JackGilmore** [comment]
Done in https://github.com/OpenDataScotland/opendata.scot_analytics
