### ISSUE TITLE
Add missing local authority data portals

### ISSUE THREAD

**Issue by JackGilmore** [OpenDataScotland/the_od_bods#68]
We currently don't have any datasets in JKAN for these local authorities. Investigate and add links to the JKAN orgs where applicable and add to scrapers where possible. If we need an additional scraper (e.g. new type of portal) then we should probably spawn another ticket to build a script.

❌ Clackmannanshire Council 
- [ ] Comhairle nan Eilean Siar
- [x] East Dunbartonshire Council
- [x] East Lothian Council
- [x] East Renfrewshire Council
- [x] Falkirk Council
- [x] Fife Council - https://know.fife.scot/
- [x] Inverclyde Council
- [x] Midlothian Council
- [ ] Orkney Islands Council
- [x] Scottish Borders Council
- [x] Shetland Islands Council
- [x] South Lanarkshire Council
- [x] West Dunbartonshire Council
- [x] West Lothian Council

**Comment by watty62** [comment]
Three OGL-licensed Open Data sets for Shetland here: 

https://www.shetland.gov.uk/downloads/download/155/map-data

**Comment by KarenJewell** [comment]
We now have all of these except Comhairle nan Eilean Siar which has a naming issue (we do have their data) #164 
and Orkney Islands Council which I will contact to ask #178

https://know.fife.scot/ has been moved to issue #165 
and Shetland to #169 

Closing this task as all others have issues to cover.
