### ISSUE TITLE
Update statistics.gov.scot datasets

### ISSUE THREAD

**Issue by JackGilmore** [OpenDataScotland/the_od_bods#70]
See Twitter post about updated datasets https://twitter.com/spokeslothian/status/1523774278143180800

**Comment by KarenJewell** [comment]
@JackGilmore is this still a separate issue or can this be part of [#114 ](https://github.com/OpenDataScotland/the_od_bods/issues/114)? I realise your original tweet says "CTC26" coming up so we didn't have automation when this was raised.

**Comment by JackGilmore** [comment]
@KarenJewell - It's the same as #114 so happy for these two to get merged together

**Comment by KarenJewell** [comment]
With CTC27 event, Issue #114 and commit https://github.com/OpenDataScotland/the_od_bods/commit/3e2a4a8072a80d625b92875458d8a23ee6bd004c statistics.gov.scot as a source is now added and issue will be closed.
