### ISSUE TITLE
Add Spatial Hub as a data source

### ISSUE THREAD

**Issue by JackGilmore** [OpenDataScotland/the_od_bods#97]
Add https://data.spatialhub.scot/dataset/ as a source

We think this might be possibly through the existing CKAN API.

Some datasets on the Spatial Hub are already published by local authorities in their individual open data portals which has the potential to cause duplicates. For example, Angus Council’s polling districts is listed on both their [CKAN instance](http://opendata.angus.gov.uk/dataset/angus-council-polling-districts), and [IS’s Spatial Hub](https://data.spatialhub.scot/dataset/polling_districts-an). We need to have a discussion around how we tackle these instances. 

- Do we consider them duplicates? 
- Do we add both records to the site or do we just add one of them? 
- If the latter option, which ones goes on the site? 

Out of the 138 datasets on the Spatial Hub, 42  of them are licensed as “not open”, meaning it would potentially be counterproductive to list them on opendata.scot as they would be inaccessible to the vast majority of people. We need to have a discussion around this and decide whether we list these datasets regardless of license or if we filter down to datasets only with an open license. If the latter option was chosen then we would need to do some work on filtering these non-open datasets by adding a new step to our pipeline.

**Comment by watty62** [comment]
Looking at Open Data only on the Spatial Hub, we have for example 

* [East Lothian](https://data.spatialhub.scot/organization/east-lothian) with 4 data sets. 
* [East Renfrewshire](https://data.spatialhub.scot/organization/east-renfrewshire) - 3 datasets
* [Falkirk](https://data.spatialhub.scot/organization/falkirk) - 1 datasets
* [Fife](https://data.spatialhub.scot/organization/fife) - 3 datasets
* [Inverclyde](https://data.spatialhub.scot/organization/inverclyde) - 3 datasets
* [Scottish Borders](https://data.spatialhub.scot/organization/scottish-borders) - 3 datasets
* [Shetland](https://data.spatialhub.scot/organization/shetland) - 3 datasets
* [South Lanarkshire](https://data.spatialhub.scot/organization/south-lanarkshire) - 3 datasets
* [West Dunbartonshire](https://data.spatialhub.scot/organization/west-dunbartonshire) - 3 datasets
* [West Lothian](https://data.spatialhub.scot/organization/west-lothian) - 4 datasets
* [Western Isles - inconsistent gaelic naming](https://data.spatialhub.scot/organization/eilean-siar) - 3 datasets


This would fix 11 of the 14  of the missing councils in [issue 68](https://github.com/OpenDataScotland/the_od_bods/issues/68) - although there may be other sources (eg see Fife on that issue).
